version: '3'
services:
  nginx:
    image: benoitlaplanche/4dvop:nginx 
    ports:
      - "8080:8080"
  haproxy:
    image: benoitlaplanche/4dvop: haproxy
    ports:
      - "80:80"
    depends_on:
      - nginx
